<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ShopBananasshelf</name>
   <tag></tag>
   <elementGuidId>b985f028-2543-4054-b72b-6663f84fd990</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ShopBananasshelf</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;content-wrapper    home-page-container&quot;]/div[@class=&quot;header-wrapper&quot;]/div[@class=&quot;brand-header-wrapper&quot;]/header[@class=&quot;brand-header brand-header--with-search brand-header--multi-search-enabled&quot;]/div[@class=&quot;brand-header__main-column&quot;]/div[@class=&quot;brand-header__navigation&quot;]/nav[@class=&quot;navigation&quot;]/ul[@class=&quot;navigation__nav-items&quot;]/li[@class=&quot;nav-item nav-item--open&quot;]/div[@class=&quot;menu-tree menu-tree--open menu-tree--department menu-tree--aisle&quot;]/div[@class=&quot;menu-tree__inner&quot;]/ul[@class=&quot;menu menu-superdepartment&quot;]/li[@class=&quot;menu-superdepartment-0 menu__item menu__item--superdepartment menu__item--active&quot;]/ul[@class=&quot;menu menu-department&quot;]/li[@class=&quot;menu-department-1 menu__item menu__item--department menu__item--active&quot;]/ul[@class=&quot;menu menu-aisle&quot;]/li[@class=&quot;menu-aisle-1 menu__item menu__item--aisle&quot;]/a[@class=&quot;menu__link menu__link--aisle&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
