export const FETCH_TEAMS = "FETCH_TEAMS";
export const NEW_TEAM = "NEW_TEAMS";
export const ADD_TEAM = "ADD_TEAM";
export const ACCEPT_INVITATION = "ACCEPT_INVITATION";
export const DECLINE_INVITATION = "DECLINE_INVITATION";
export const FETCH_INVITATIONS = "FETCH_INVITATIONS";
export const FETCH_MESSAGES = "FETCH_INVITATIONS";
export const SEND_MESSAGE = "SEND_MESSAGE";
