<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Weight</name>
   <tag></tag>
   <elementGuidId>f1e9f4a8-f3a4-45c1-bb82-1561a909e5ec</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auto</name>
      <type>Main</type>
      <value>controls-weight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>controls--weight controls--unit-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;275280804&quot;)/div[@class=&quot;product-controls--wrapper&quot;]/form[1]/div[@class=&quot;controls&quot;]/div[@class=&quot;controls--unit-toggle&quot;]/fieldset[1]/div[2]/span[@class=&quot;display-only-in-js&quot;]/label[@class=&quot;controls--weight controls--unit-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
