FROM golang:1.10.1-alpine3.7
RUN apk update && apk add git tree make bash

#install libraries
RUN go get -v gopkg.in/check.v1 github.com/tebeka/go2xunit github.com/lib/pq github.com/gorilla/mux

#set up workdir
ENV GOBIN /go/bin
WORKDIR /go/src/go-ci-test
COPY . .
RUN pwd
RUN tree