<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ui-component__icon--check</name>
   <tag></tag>
   <elementGuidId>33b2fa25-7021-4824-9281-be7f91f31761</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-component__icon--checkmark</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>155</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketing-field-set&quot;)/div[@class=&quot;marketing-preferences&quot;]/div[2]/div[@class=&quot;ui-component__checkbox-wrapper&quot;]/label[@class=&quot;ui-component__checkbox-label&quot;]/span[@class=&quot;ui-component__dummy-checkbox&quot;]/span[@class=&quot;ui-component__icon--checkmark&quot;]</value>
   </webElementProperties>
</WebElementEntity>
